export const sampleMovies = [
    {
        title: 'Avengers: Endgame',
        description: 'The Avengers assemble once more to reverse an irreversible loss and defend the future.',
        genre: 'Action / Sci-Fi',
        language: 'English',
        durationMinutes: 181,
        rating: 8.4,
        posterUrl: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    },
    {
        title: 'The Dark Knight',
        description: 'A determined hero faces a criminal force that turns Gotham into a test of conviction.',
        genre: 'Action / Crime',
        language: 'English',
        durationMinutes: 152,
        rating: 9.0,
        posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    },
    {
        title: 'Inception',
        description: 'A specialist in extracting secrets through dreams is offered a chance at redemption.',
        genre: 'Sci-Fi / Thriller',
        language: 'English',
        durationMinutes: 148,
        rating: 8.8,
        posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    },
    {
        title: 'Dune',
        description: 'A gifted heir must cross a dangerous desert world to protect his family and its future.',
        genre: 'Sci-Fi / Adventure',
        language: 'English',
        durationMinutes: 155,
        rating: 8.0,
        posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    },
    {
        title: 'Oppenheimer',
        description: 'A brilliant physicist leads a historic project while wrestling with its consequence.',
        genre: 'Drama / History',
        language: 'English',
        durationMinutes: 180,
        rating: 8.6,
        posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    },
];
